### ISSUE TITLE
When makemigrations for a legacy project, always show error "Invalid object name 'django_apscheduler_djangojob'"

### ISSUE THREAD

**Issue by fbilo** [jcass77/django-apscheduler#130]
**Describe the bug / feature**
I have a legacy project, which utilized django-apscheduler, and use sql server as Django database backend. The original deployment had been totally destroyed. So I have to deploy all stuffs in a new server. However, when I try to execute command line python manage.py makemigrations, the log shows it always login into sql server to execute a query, and then failed by the "Invalid object name 'django_apscheduler_djangojob'" error.

**To Reproduce**
Execute command line python manage.py makemigrations

**Expected behavior**
No errors show happen. SQL Statements should be generated.

**Screenshots**
The error logs like this:
(KBS) PS C:\KBS_PY\KBS> python manage.py makemigrations
DRIVER=ODBC Driver 17 for SQL Server;SERVER=localhost\SQLEXPRES,1433;UID=xxxxx;PWD=xxxxx;DATABASE=AI;MARS_Connection=yes
Traceback (most recent call last):
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\KBS_PY\KBS\lib\site-packages\sql_server\pyodbc\base.py", line 554, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'django_apscheduler_djangojob'. (208) (SQLExecDirectW); [42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\KBS_PY\KBS\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\KBS_PY\KBS\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\KBS_PY\KBS\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\KBS_PY\KBS\lib\site-packages\django\core\management\base.py", line 368, in execute
    self.check()
  File "C:\KBS_PY\KBS\lib\site-packages\django\core\management\base.py", line 396, in check
    databases=databases,
  File "C:\KBS_PY\KBS\lib\site-packages\django\core\checks\registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\KBS_PY\KBS\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\KBS_PY\KBS\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\KBS_PY\KBS\lib\site-packages\django\urls\resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "C:\KBS_PY\KBS\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\KBS_PY\KBS\lib\site-packages\django\urls\resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\KBS_PY\KBS\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\KBS_PY\KBS\lib\site-packages\django\urls\resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\KBS_PY\KBS\KBS\urls.py", line 28, in <module>
    url(r'^api/v1/', include('KBS.apiVersion')),
  File "C:\KBS_PY\KBS\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\KBS_PY\KBS\KBS\apiVersion.py", line 36, in <module>
    from Report.views import ReportViewSet, ReportTitleViewSet, ReportTrendViewSet, ReportPackageViewSet, ReportFaqViewSet, \
  File "C:\KBS_PY\KBS\Report\views.py", line 388, in <module>
    scheduler.start()
  File "C:\KBS_PY\KBS\lib\site-packages\apscheduler\schedulers\background.py", line 33, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "C:\KBS_PY\KBS\lib\site-packages\apscheduler\schedulers\base.py", line 162, in start
    self._real_add_job(job, jobstore_alias, replace_existing)
  File "C:\KBS_PY\KBS\lib\site-packages\apscheduler\schedulers\base.py", line 867, in _real_add_job
    store.add_job(job)
  File "C:\KBS_PY\KBS\lib\site-packages\django_apscheduler\jobstores.py", line 236, in add_job
    job_state=pickle.dumps(job.__getstate__(), self.pickle_protocol),
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\models\query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\models\base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\models\base.py", line 792, in save_base
    force_update, using, update_fields,
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\models\base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\KBS_PY\KBS\lib\site-packages\sql_server\pyodbc\base.py", line 554, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'django_apscheduler_djangojob'. (208) (SQLExecDirectW); [42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")

**Comment by jcass77** [comment]
>File "C:\KBS_PY\KBS\Report\views.py", line 388, in 
scheduler.start()

It looks like one of your views is trying to start up a background job during import time. That won't work as `makemigrations` hasn't had an opportunity to create the database tables yet.

Using background job schedulers comes with its own unique set of challenges, and it might be best to switch to using a blocking scheduler instead (more details in the README).

You should also be aware that MSSQL is not officially supported by Django, and a number of users have reported issues when trying to run django-apscheduler on that particular database (see #93).

**Comment by fbilo** [comment]
@jcass77 
Thanks John, I fixed by commented all start backgound job codes, switch to use a sqlite db, then migrate the models, migrate the django-apscheduler, all these works well.

However, when I uncommented those start job lines, then execute python manage.py migrate again, I got an error :
_"Traceback (most recent call last):
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\KBS_PY\KBS\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: django_apscheduler_djangojob.id"_

Any idea to fix it?

Thanks~
fbilo

**Comment by jcass77** [comment]
It looks like the `UNIQUE` constraint is failing.

Maybe check your database to see if there are any duplicate `django_apscheduler_djangojob.id` entries in the data?

**Comment by fbilo** [comment]
@jcass77 
I used the sqlite3.exe to open the db.sqlite3, found there is a record for the job already exist, and it turned out that when I started the web site by call Python.exe manage.py runserver everytime, the apscheduler will try to add a job record, if found a existed one, it will only throw an exception, but not reuse the existed one. So I have to delete the records every time before start the web site, This looks weird, doesn't it?

**Comment by jcass77** [comment]
This should not happen under normal conditions; perhaps check the APScheduler documentation on [adding jobs](https://apscheduler.readthedocs.io/en/stable/userguide.html?highlight=add_job#adding-jobs) to verify your approach:

> If you schedule jobs in a persistent job store during your application’s initialization, you MUST define an explicit ID for the job and use replace_existing=True or you will get a new copy of the job every time your application restarts!

**Comment by fbilo** [comment]
> This should not happen under normal conditions; perhaps check the APScheduler documentation on [adding jobs](https://apscheduler.readthedocs.io/en/stable/userguide.html?highlight=add_job#adding-jobs) to verify your approach:
> 
> > If you schedule jobs in a persistent job store during your application’s initialization, you MUST define an explicit ID for the job and use replace_existing=True or you will get a new copy of the job every time your application restarts!

Cool, I fixed it. Thanks a lot!

**Comment by fbilo** [comment]
Closed as by design?
