### ISSUE TITLE
django.db.utils.ProgrammingError: relation "django_apscheduler_djangojob" does not exist

### ISSUE THREAD

**Issue by ytpl65** [jcass77/django-apscheduler#162]
The problem is when i run python manage.py migrate, the migrations are correctly applied to default DB, but when i run with --database=xyz option, it failed to apply all migrations here is the settings.py(limited) and the  error...
`
#settings.py
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #third_party_apps
    'django_apscheduler',
    ...',
    #my_apps
    '...',
    ]

APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25 

DATABASES = {
'default':{---},
'xyz':{...}
}
 `

`Applying django_apscheduler.0001_initial... OK
  Applying django_apscheduler.0002_auto_20180412_0758... OK
  Applying django_apscheduler.0003_auto_20200716_1632... OK
  Applying django_apscheduler.0004_auto_20200717_1043... OK
  Applying django_apscheduler.0005_migrate_name_to_id...Traceback (most recent call last):
  File "*/*/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_apscheduler_djangojob" does not exist
LINE 1: ..., "django_apscheduler_djangojob"."job_state" FROM "django_ap...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "..../manage.py", line 22, in <module>
    main()
  File "..../manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/..../python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/..../python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/..../python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/..../python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/..../python3.9/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/..../python3.9/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/..../python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/..../python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/..../python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/..../python3.9/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/..../python3.9/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/..../python3.9/site-packages/django_apscheduler/migrations/0005_migrate_name_to_id.py", line 14, in migrate_name_to_id
    for job in JobModel.objects.all():
  File "/..../python3.9/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/..../python3.9/site-packages/django/db/models/query.py", line 1303, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/..../python3.9/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/..../python3.9/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "/..../python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/..../python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/..../python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/..../python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/..../python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/..../python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_apscheduler_djangojob" does not exist
LINE 1: ..., "django_apscheduler_djangojob"."job_state" FROM "django_ap...

`

**Comment by jcass77** [comment]
django-apscheduler does not do anything special about migrations - it relies on the standard Django behaviour.

If you used the default database before, and are now trying to rename it, then it might be worth a try to drop the existing database first and clean up all migrations and recreate everything from scratch.

Closing for now, please reopen if you have any new information to add.

**Comment by MinSiThu** [comment]
## Same Problem

#### I am having the same problem here, if you guys had already solved this problem, please let me know. I dropped the existing database and created new database.

I did *makemigrations* on local machine and put it on linux server and *migrate*.
But I can't move on because of the following errors.


```bash
django.db.utils.ProgrammingError: (1146, "Table 'appname.django_apscheduler_djangojob' doesn't exist")
```

**Comment by Chukwujiobi-Canon** [comment]
Same here:
```
django.db.utils.ProgrammingError: (1146, "Table 'appname.django_apscheduler_djangojob' doesn't exist")
```
