### ISSUE TITLE
Unapplying Migrations Fails

### ISSUE THREAD

**Issue by n4ff4h** [jcass77/django-apscheduler#185]
When trying to uninstall this library, I did a `python manage.py migrate django_apscheduler zero` and the following errors throws up:

```bash
Operations to perform:
  Unapply all migrations: django_apscheduler
Running migrations:
  Rendering model states... DONE
  Unapplying django_apscheduler.0009_djangojobexecution_unique_job_executions... OK
  Unapplying django_apscheduler.0008_remove_djangojobexecution_started... OK
  Unapplying django_apscheduler.0007_auto_20200717_1404... OK
  Unapplying django_apscheduler.0006_remove_djangojob_name... OK
  Unapplying django_apscheduler.0005_migrate_name_to_id...Traceback (most recent call last):
  File "/Users/naffah/Code/PythonProjects/erp_integrator/manage.py", line 22, in <module>
    main()
  File "/Users/naffah/Code/PythonProjects/erp_integrator/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/naffah/Library/Caches/pypoetry/virtualenvs/erp-integrator-NtQaQ5xa-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/naffah/Library/Caches/pypoetry/virtualenvs/erp-integrator-NtQaQ5xa-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/naffah/Library/Caches/pypoetry/virtualenvs/erp-integrator-NtQaQ5xa-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/naffah/Library/Caches/pypoetry/virtualenvs/erp-integrator-NtQaQ5xa-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naffah/Library/Caches/pypoetry/virtualenvs/erp-integrator-NtQaQ5xa-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naffah/Library/Caches/pypoetry/virtualenvs/erp-integrator-NtQaQ5xa-py3.11/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/Users/naffah/Library/Caches/pypoetry/virtualenvs/erp-integrator-NtQaQ5xa-py3.11/lib/python3.11/site-packages/django/db/migrations/executor.py", line 141, in migrate
    state = self._migrate_all_backwards(plan, full_plan, fake=fake)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naffah/Library/Caches/pypoetry/virtualenvs/erp-integrator-NtQaQ5xa-py3.11/lib/python3.11/site-packages/django/db/migrations/executor.py", line 219, in _migrate_all_backwards
    self.unapply_migration(states[migration], migration, fake=fake)
  File "/Users/naffah/Library/Caches/pypoetry/virtualenvs/erp-integrator-NtQaQ5xa-py3.11/lib/python3.11/site-packages/django/db/migrations/executor.py", line 279, in unapply_migration
    state = migration.unapply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naffah/Library/Caches/pypoetry/virtualenvs/erp-integrator-NtQaQ5xa-py3.11/lib/python3.11/site-packages/django/db/migrations/migration.py", line 159, in unapply
    raise IrreversibleError(
django.db.migrations.exceptions.IrreversibleError: Operation <RunPython <function migrate_name_to_id at 0x136aacf40>> in django_apscheduler.0005_migrate_name_to_id is not reversible
```

Any ideas on how to fix this?

**Comment by eduardopdev** [comment]
Hello, are you still dealing with this problem?

**Comment by spumer** [comment]
Got same on fresh install with mariadb

```
services:
  mariadb:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    restart: unless-stopped
```

```
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying django_apscheduler.0001_initial... OK
  Applying django_apscheduler.0002_auto_20180412_0758... OK
  Applying django_apscheduler.0003_auto_20200716_1632... OK
  Applying django_apscheduler.0004_auto_20200717_1043... OK
  Applying django_apscheduler.0005_migrate_name_to_id...ERROR
test setup failed
self = <mysql.connector.connection_cext.CMySQLConnection object at 0x112ced5b0>
query = b'SELECT `django_apscheduler_djangojob`.`id`, `django_apscheduler_djangojob`.`name`, `django_apscheduler_djangojob`.`n...djangojob`.`job_state` FROM `django_apscheduler_djangojob` ORDER BY `django_apscheduler_djangojob`.`next_run_time` ASC'
raw = False, buffered = False, raw_as_string = False

    @with_context_propagation
    def cmd_query(
        self,
        query: StrOrBytes,
        raw: Optional[bool] = None,
        buffered: bool = False,
        raw_as_string: bool = False,
    ) -> Optional[Union[CextEofPacketType, CextResultType]]:
        """Send a query to the MySQL server"""
        self.handle_unread_result()
        if raw is None:
            raw = self._raw
        try:
            if not isinstance(query, bytes):
                query = query.encode("utf-8")
>           self._cmysql.query(
                query,
                raw=raw,
                buffered=buffered,
                raw_as_string=raw_as_string,
                query_attrs=self.query_attrs,
            )
E           _mysql_connector.MySQLInterfaceError: Unknown column 'django_apscheduler_djangojob.name' in 'field list'

../../../.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py:706: MySQLInterfaceError

The above exception was the direct cause of the following exception:

self = <django.db.backends.utils.CursorWrapper object at 0x1130bd280>
sql = 'SELECT `django_apscheduler_djangojob`.`id`, `django_apscheduler_djangojob`.`name`, `django_apscheduler_djangojob`.`ne...djangojob`.`job_state` FROM `django_apscheduler_djangojob` ORDER BY `django_apscheduler_djangojob`.`next_run_time` ASC'
params = ()
ignored_wrapper_args = (False, {'connection': <DatabaseWrapper vendor='mysql' alias='default'>, 'cursor': <django.db.backends.utils.CursorWrapper object at 0x1130bd280>})

    def _execute(self, sql, params, *ignored_wrapper_args):
        # Raise a warning during app initialization (stored_app_configs is only
        # ever set during testing).
        if not apps.ready and not apps.stored_app_configs:
            warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)
        self.db.validate_no_broken_transaction()
        with self.db.wrap_database_errors:
            if params is None:
                # params default might be backend specific.
                return self.cursor.execute(sql)
            else:
>               return self.cursor.execute(sql, params)

../../../.venv/lib/python3.12/site-packages/django/db/backends/utils.py:105: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.venv/lib/python3.12/site-packages/mysql/connector/django/base.py:188: in execute
    return self.cursor.execute(query, new_args)
../../../.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py:357: in execute
    result = self._connection.cmd_query(
../../../.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py:97: in wrapper
    return method(cnx, *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mysql.connector.connection_cext.CMySQLConnection object at 0x112ced5b0>
query = b'SELECT `django_apscheduler_djangojob`.`id`, `django_apscheduler_djangojob`.`name`, `django_apscheduler_djangojob`.`n...djangojob`.`job_state` FROM `django_apscheduler_djangojob` ORDER BY `django_apscheduler_djangojob`.`next_run_time` ASC'
raw = False, buffered = False, raw_as_string = False

    @with_context_propagation
    def cmd_query(
        self,
        query: StrOrBytes,
        raw: Optional[bool] = None,
        buffered: bool = False,
        raw_as_string: bool = False,
    ) -> Optional[Union[CextEofPacketType, CextResultType]]:
        """Send a query to the MySQL server"""
        self.handle_unread_result()
        if raw is None:
            raw = self._raw
        try:
            if not isinstance(query, bytes):
                query = query.encode("utf-8")
            self._cmysql.query(
                query,
                raw=raw,
                buffered=buffered,
                raw_as_string=raw_as_string,
                query_attrs=self.query_attrs,
            )
        except MySQLInterfaceError as err:
>           raise get_mysql_exception(
                err.errno, msg=err.msg, sqlstate=err.sqlstate
            ) from err
E           mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'django_apscheduler_djangojob.name' in 'field list'

../../../.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py:714: ProgrammingError

The above exception was the direct cause of the following exception:

request = <SubRequest '_django_db_marker' for <Function test_upload_demo[.dem]>>

    @pytest.fixture(autouse=True)
    def _django_db_marker(request: pytest.FixtureRequest) -> None:
        """Implement the django_db marker, internal to pytest-django."""
        marker = request.node.get_closest_marker("django_db")
        if marker:
>           request.getfixturevalue("_django_db_helper")

../../../.venv/lib/python3.12/site-packages/pytest_django/plugin.py:533: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.venv/lib/python3.12/site-packages/pytest_django/fixtures.py:144: in django_db_setup
    db_cfg = setup_databases(
../../../.venv/lib/python3.12/site-packages/django/test/utils.py:206: in setup_databases
    connection.creation.create_test_db(
../../../.venv/lib/python3.12/site-packages/django/db/backends/base/creation.py:78: in create_test_db
    call_command(
../../../.venv/lib/python3.12/site-packages/django/core/management/__init__.py:194: in call_command
    return command.execute(*args, **defaults)
../../../.venv/lib/python3.12/site-packages/django/core/management/base.py:459: in execute
    output = self.handle(*args, **options)
../../../.venv/lib/python3.12/site-packages/django/core/management/base.py:107: in wrapper
    res = handle_func(*args, **kwargs)
../../../.venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py:357: in handle
    post_migrate_state = executor.migrate(
../../../.venv/lib/python3.12/site-packages/django/db/migrations/executor.py:135: in migrate
    state = self._migrate_all_forwards(
../../../.venv/lib/python3.12/site-packages/django/db/migrations/executor.py:167: in _migrate_all_forwards
    state = self.apply_migration(
../../../.venv/lib/python3.12/site-packages/django/db/migrations/executor.py:255: in apply_migration
    state = migration.apply(state, schema_editor)
../../../.venv/lib/python3.12/site-packages/django/db/migrations/migration.py:127: in apply
    operation.database_forwards(
../../../.venv/lib/python3.12/site-packages/django/db/migrations/operations/special.py:196: in database_forwards
    self.code(from_state.apps, schema_editor)
../../../.venv/lib/python3.12/site-packages/django_apscheduler/migrations/0005_migrate_name_to_id.py:14: in migrate_name_to_id
    for job in JobModel.objects.all():
../../../.venv/lib/python3.12/site-packages/django/db/models/query.py:400: in __iter__
    self._fetch_all()
../../../.venv/lib/python3.12/site-packages/django/db/models/query.py:1928: in _fetch_all
    self._result_cache = list(self._iterable_class(self))
../../../.venv/lib/python3.12/site-packages/django/db/models/query.py:91: in __iter__
    results = compiler.execute_sql(
../../../.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py:1574: in execute_sql
    cursor.execute(sql, params)
../../../.venv/lib/python3.12/site-packages/django/db/backends/utils.py:79: in execute
    return self._execute_with_wrappers(
../../../.venv/lib/python3.12/site-packages/django/db/backends/utils.py:92: in _execute_with_wrappers
    return executor(sql, params, many, context)
../../../.venv/lib/python3.12/site-packages/django/db/backends/utils.py:100: in _execute
    with self.db.wrap_database_errors:
../../../.venv/lib/python3.12/site-packages/django/db/utils.py:91: in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
../../../.venv/lib/python3.12/site-packages/django/db/backends/utils.py:105: in _execute
    return self.cursor.execute(sql, params)
../../../.venv/lib/python3.12/site-packages/mysql/connector/django/base.py:188: in execute
    return self.cursor.execute(query, new_args)
../../../.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py:357: in execute
    result = self._connection.cmd_query(
../../../.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py:97: in wrapper
    return method(cnx, *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mysql.connector.connection_cext.CMySQLConnection object at 0x112ced5b0>
query = b'SELECT `django_apscheduler_djangojob`.`id`, `django_apscheduler_djangojob`.`name`, `django_apscheduler_djangojob`.`n...djangojob`.`job_state` FROM `django_apscheduler_djangojob` ORDER BY `django_apscheduler_djangojob`.`next_run_time` ASC'
raw = False, buffered = False, raw_as_string = False

    @with_context_propagation
    def cmd_query(
        self,
        query: StrOrBytes,
        raw: Optional[bool] = None,
        buffered: bool = False,
        raw_as_string: bool = False,
    ) -> Optional[Union[CextEofPacketType, CextResultType]]:
        """Send a query to the MySQL server"""
        self.handle_unread_result()
        if raw is None:
            raw = self._raw
        try:
            if not isinstance(query, bytes):
                query = query.encode("utf-8")
            self._cmysql.query(
                query,
                raw=raw,
                buffered=buffered,
                raw_as_string=raw_as_string,
                query_attrs=self.query_attrs,
            )
        except MySQLInterfaceError as err:
>           raise get_mysql_exception(
                err.errno, msg=err.msg, sqlstate=err.sqlstate
            ) from err
E           django.db.utils.ProgrammingError: (1054, "1054 (42S22): Unknown column 'django_apscheduler_djangojob.name' in 'field list'", '42S22')

../../../.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py:714: ProgrammingError
```

**Comment by danjac** [comment]
I have run into the same issue.
